### ISSUE TITLE
AttributeError: module 'torchvision.transforms.functional' has no attribute 'get_dimensions'

### ISSUE THREAD

**Issue by JulienMaufront** [teamtomo/fidder#13]
Hello,

When I try to use "fidder predict" command, I get an error message : "AttributeError: module 'torchvision.transforms.functional' has no attribute 'get_dimensions'"
Do you know how I can set this up ?

Thank you,
Cheers

Julien Maufront

**Comment by JulienMaufront** [comment]
Oh that's wonderful, thank you !

**Comment by JulienMaufront** [comment]
Hello Alister,

I'm so sorry, actually I just had to upgrade my pytorch version and now it works like a charm !  
I hope I haven't wasted too much of your time making you look for this issue.

Thanks again !

**Comment by alisterburt** [comment]
Hey Julien! Thanks for reporting back in - I did some quick tests and couldn't see anything wrong but wanted to check a bit more before telling you it was something your end, glad it's working for you! 

Would be curious to hear about performance too, feel free to drop me an email with any thoughts!
