### ISSUE TITLE
Using another trained model

### ISSUE THREAD

**Issue by hamid13r** [teamtomo/fidder#22]
Hi Alister!

I have been using fidder and really like the results. I have been using Warp-generated masks which needed to be resized and rotated. Now I want to use our trained model for apix=1.66 to predict and generate with fidder so I don't have to rely on Warp masks. However, I couldn't see how to do that in the code. 

Can you please point me in the right direction please?

Best,
Hamid

**Comment by alisterburt** [comment]
Hey @hamid13r !

> I have been using fidder and really like the results.

Glad you're finding it useful!

It sounds like you're trying to use a BoxNet model with fidder? This is not possible.

What you can do is
- retrain fidder on your own data using the `fidder train` CLI (expected input is a folder containing folders called 'images' and 'masks' containing identically named tiff files.)
- run `fidder predict` with your new model checkpoint to generate a mask
- run `fidder erase` on your images with the new mask

Is `fidder predict` not performing well for you? or are you erasing something else?

**Comment by alisterburt** [comment]
@hamid13r I wouldn't expect fidder to work well on those data - it hasn't been trained to recognise them. 

If you're open to sharing data we could easily make a sister package 'desputterer' for removing this secondary sputter 🙂

**Comment by alisterburt** [comment]
Cool, please could you send them my way? Going to close this now
