### ISSUE TITLE
running Fidder on raw frames from tilt series

### ISSUE THREAD

**Issue by karine-jan** [teamtomo/fidder#30]
I have tried to run Fidder on non-motion corrected raw tilt (TS_45_000_-0.0_raw.mrc) of the EMPIAR-10164 (TeamTomo tutorial).
The .mrc file has 10 frames and Fidder iterates over each one without any error but after iteration 9 it is killed
<img width="1032" alt="Screenshot 2023-06-21 163137" src="https://github.com/teamtomo/fidder/assets/130336394/1ba59773-5074-4e0d-9ba3-5a7c42237c0a">

**Comment by alisterburt** [comment]
hey @karine-jan - thanks for the traceback

Have you checked out memory usage whilst it's running? It's probably an out of memory error, those images are super-resoluiton (~8k x ~8k).

As discussed on the mailing list - running fidder on frames from a tilt-series doesn't make much sense, it should be run on a tilt-image or tilt-series.
