### ISSUE TITLE
DistBackendError:NCCL error when running fidder predict

### ISSUE THREAD

**Issue by fg1215** [teamtomo/fidder#32]
I am trying to run the following command
`fidder predict --input-image ReconstructTomograms/job009/tomograms/rec_lmla_105_ts_002.mrc --probability-threshold 0.5 --output-mask ReconstructTomograms/job009/mask.mrc`
Here is my LD_LIBRARY_PATH
`/net/nfs1/public/EM/CUDA/cuda-11.2.2/lib64:/lmb/home/fgao/micromamba/envs/fidder/lib/python3.10/site-packages/nvidia/nvjitlink/lib`

See error log attached.
[fidder_output.txt](https://github.com/teamtomo/fidder/files/13635121/fidder_output.txt)

Thank you!

**Comment by fg1215** [comment]
[environment_params.txt](https://github.com/teamtomo/fidder/files/13662678/environment_params.txt)
Also see environment parameters if this helps!
Best wishes,
Forson

**Comment by alisterburt** [comment]
haven't heard any other complaints about this and from googling it seems like it was a temporary ecosystem level thing :-)
