### ISSUE TITLE
About current state and possible integration in Scipion

### ISSUE THREAD

**Issue by JorMaister** [teamtomo/fidder#33]
Hi, @alisterburt,

I'm Jorge from Scipion team. We're looking to integrate some tool that removes the fiducial markers from the tilt-series and heard about fidder. I'd like to know the current state of fidder as a general tool for that purpose and if it's ok to carry out the integration within Scipion framework. 

Many thanks!

**Comment by alisterburt** [comment]
Hey @JorMaister ! 

Thanks for reaching out - I haven't touched the repo in a while but everything should work fine! You're free to integrate if it's useful and I'm happy to work with you to improve things if it doesn't quite work for whatever reason.

The general model is okay but hasn't seen a huge amount of data... someone over on image.sc has retrained it recently with success too https://forum.image.sc/t/does-pixel-size-matter-for-retraining-fidder/97370

**Comment by JorMaister** [comment]
Many thanks, @alisterburt!

I'll let you know how it goes.

Have a good day!

**Comment by alisterburt** [comment]
Right back at you! Will close here but do reach out if you come up against any issues

**Comment by JorMaister** [comment]
Sure!
