### ISSUE TITLE
fidder抓取app

### ISSUE THREAD

**Issue by 77599** [teamtomo/fidder#36]
你好，请问fidder怎么抓取app呀，我手机电脑连上之后，手机app显示网络错误

**Comment by 77599** [comment]
Hello, alisterburt, I'm sorry to bother you again, I still have some problems with the fidder scraping app, after my mobile phone is connected, the mobile app shows a network error, how to solve this problem, I sincerely hope you can give me some help ...

**Comment by alisterburt** [comment]
This is not the repository for a mobile scraping app

**Comment by 77599** [comment]
I see, I feel like the mouth is open, thank you very much. If it weren't for you, I might still be stumbling on fidder, I've read a lot of bloggers' articles, and most of them are saying that they use fidder. Do you have any recommended libraries? Because I need to crawl some data on the app for my completion, I need this very much.
